/**
 * Plugin Manager service: TAK.gov link state + plugin storage under data/plugins.
 * Uses TAK.gov OAuth 2.0 Device Authorization Grant (same as OpenTAKServer).
 * TAK.gov returns 421 if not using HTTP/2, so we use Node's http2 module.
 * See: https://raw.githubusercontent.com/brian7704/OpenTAKServer/master/opentakserver/blueprints/ots_api/tak_gov_link_api.py
 */

const fs = require("fs");
const path = require("path");
const http2 = require("http2");
const { URL } = require("url");

const DATA_DIR = path.join(__dirname, "..", "data");
const PLUGINS_DIR = path.join(DATA_DIR, "plugins");
const MANIFEST_PATH = path.join(DATA_DIR, "plugin-manifest.json");

const TAK_GOV_DEVICE_URL = "https://auth.tak.gov/auth/realms/TPC/protocol/openid-connect/auth/device";
const TAK_GOV_TOKEN_URL = "https://auth.tak.gov/auth/realms/TPC/protocol/openid-connect/token";
const TAK_GOV_CLIENT_ID = "tak-gov-eud";
// Match OpenTAKServer User-Agent; TAK.gov may expect it
const USER_AGENT = "OpenTAKServer 1.7.9";

/**
 * POST to a TAK.gov URL using HTTP/2 (required; TAK.gov returns 421 over HTTP/1.1).
 * @param {string} url - full URL
 * @param {string} formBody - application/x-www-form-urlencoded body
 * @returns {Promise<{ statusCode: number, data: object }>}
 */
function takGovHttp2Post(url, formBody) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const host = u.hostname;
    const pathname = u.pathname || "/";
    const timeout = 15000;

    const client = http2.connect(url, {
      servername: host,
    });
    let timeoutId;
    const cleanup = () => {
      clearTimeout(timeoutId);
      client.close();
    };
    timeoutId = setTimeout(() => {
      cleanup();
      reject(new Error("TAK.gov request timeout"));
    }, timeout);

    const headers = {
      ":path": pathname,
      ":method": "POST",
      "content-type": "application/x-www-form-urlencoded",
      "user-agent": USER_AGENT,
    };
    const req = client.request(headers);
    let body = "";
    req.setEncoding("utf8");
    req.on("response", (responseHeaders) => {
      const status = Number(responseHeaders[":status"]) || 0;
      req.on("data", (chunk) => { body += chunk; });
      req.on("end", () => {
        cleanup();
        let data;
        try {
          data = body ? JSON.parse(body) : {};
        } catch (_) {
          data = { raw: body };
        }
        resolve({ statusCode: status, data });
      });
    });
    req.on("error", (err) => {
      cleanup();
      reject(err);
    });
    req.write(formBody);
    req.end();
  });
}

function ensurePluginsDir() {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  if (!fs.existsSync(PLUGINS_DIR)) fs.mkdirSync(PLUGINS_DIR, { recursive: true });
}

function loadManifest() {
  ensurePluginsDir();
  if (!fs.existsSync(MANIFEST_PATH)) {
    return {
      takGovLink: { linked: false, linkCode: null, linkCodeExpiry: null },
      plugins: [],
    };
  }
  try {
    const raw = fs.readFileSync(MANIFEST_PATH, "utf8");
    const data = JSON.parse(raw);
    const plugins = Array.isArray(data.plugins) ? data.plugins : [];
    const takGovLink = data.takGovLink && typeof data.takGovLink === "object"
      ? data.takGovLink
      : { linked: false, linkCode: null, linkCodeExpiry: null };
    return { takGovLink, plugins };
  } catch (err) {
    console.warn("[plugins.service] Failed to read manifest:", err?.message || err);
    return {
      takGovLink: { linked: false, linkCode: null, linkCodeExpiry: null },
      plugins: [],
    };
  }
}

function saveManifest(manifest) {
  ensurePluginsDir();
  const payload = {
    takGovLink: manifest.takGovLink || { linked: false, linkCode: null, linkCodeExpiry: null },
    plugins: Array.isArray(manifest.plugins) ? manifest.plugins : [],
  };
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(payload, null, 2));
}

/**
 * Get current TAK.gov link status. If generateNewCode is true, request a new user_code from TAK.gov
 * (OAuth 2.0 Device Authorization Grant). The code is issued by TAK.gov, not generated by us.
 * @param {boolean} generateNewCode - if true, call TAK.gov device endpoint and store device_code + user_code
 * @returns {Promise<{ linked: boolean, linkCode?: string, linkCodeExpiry?: number, verificationUri?: string, message?: string, error?: string }>}
 */
async function getTakGovLinkState(generateNewCode = false) {
  const manifest = loadManifest();
  const { takGovLink } = manifest;

  if (generateNewCode) {
    try {
      const formBody = new URLSearchParams({
        client_id: TAK_GOV_CLIENT_ID,
        scope: "openid offline_access email profile",
        grant_type: "urn:ietf:params:oauth:grant-type:device_code",
      }).toString();
      const { statusCode, data } = await takGovHttp2Post(TAK_GOV_DEVICE_URL, formBody);

      if (statusCode !== 200) {
        const msg = data.error_description || data.error || `TAK.gov returned ${statusCode}`;
        console.warn("[plugins.service] TAK.gov device request failed:", statusCode, msg);
        return { linked: !!takGovLink.linked, error: msg };
      }

      const userCode = data.user_code;
      const deviceCode = data.device_code;
      const expiresIn = typeof data.expires_in === "number" ? data.expires_in : 180;
      const interval = typeof data.interval === "number" ? data.interval : 5;
      const verificationUri = data.verification_uri || "https://tak.gov/register-device";
      const expiry = Date.now() + expiresIn * 1000;

      const updated = {
        ...takGovLink,
        linkCode: userCode,
        linkCodeExpiry: expiry,
        deviceCode,
        deviceCodeExpiry: expiry,
        interval,
        verificationUri,
      };
      saveManifest({ ...manifest, takGovLink: updated });
      return {
        linked: !!takGovLink.linked,
        linkCode: userCode,
        linkCodeExpiry: expiry,
        verificationUri,
        message: `Enter this code at ${verificationUri} (expires in ${Math.floor(expiresIn / 60)} minutes).`,
      };
    } catch (err) {
      const msg = err?.message || "Failed to get link code from TAK.gov.";
      console.warn("[plugins.service] TAK.gov device request failed:", msg);
      return {
        linked: !!takGovLink.linked,
        error: msg,
      };
    }
  }

  const hasValidCode = takGovLink.linkCode && takGovLink.linkCodeExpiry && Date.now() < takGovLink.linkCodeExpiry;
  return {
    linked: !!takGovLink.linked,
    linkCode: hasValidCode ? takGovLink.linkCode : null,
    linkCodeExpiry: takGovLink.linkCodeExpiry || null,
    verificationUri: takGovLink.verificationUri || "https://tak.gov/register-device",
  };
}

/**
 * Exchange the stored device_code for tokens (after user has entered user_code on TAK.gov and authorized).
 * No code parameter: we use the device_code stored when "Get Link Code" was called.
 * @returns {Promise<{ success: boolean, message?: string }>}
 */
async function linkTakGovAccount() {
  const manifest = loadManifest();
  const { takGovLink } = manifest;
  const deviceCode = takGovLink.deviceCode;
  if (!deviceCode) {
    return { success: false, message: "No device code. Click \"Get Link Code\" first, then enter that code at TAK.gov and authorize." };
  }
  if (takGovLink.deviceCodeExpiry && Date.now() >= takGovLink.deviceCodeExpiry) {
    return { success: false, message: "Link code expired. Click \"Get Link Code\" to get a new one." };
  }

  try {
    const formBody = new URLSearchParams({
      grant_type: "urn:ietf:params:oauth:grant-type:device_code",
      device_code: deviceCode,
      client_id: TAK_GOV_CLIENT_ID,
    }).toString();
    const { statusCode, data } = await takGovHttp2Post(TAK_GOV_TOKEN_URL, formBody);

    if (statusCode === 200 && data.access_token) {
      const refreshToken = data.refresh_token;
      const updated = {
        ...takGovLink,
        linked: true,
        refreshToken,
        linkCode: null,
        linkCodeExpiry: null,
        deviceCode: null,
        deviceCodeExpiry: null,
        interval: null,
        verificationUri: null,
      };
      saveManifest({ ...manifest, takGovLink: updated });
      return { success: true, message: "TAK.gov account linked successfully." };
    }

    const err = data?.error;
    const desc = data?.error_description || err;
    if (err === "authorization_pending") {
      return { success: false, message: "Enter the code on TAK.gov and complete authorization, then click \"Link Account\" again." };
    }
    if (err === "expired_token") {
      return { success: false, message: "Link code expired. Click \"Get Link Code\" to get a new one." };
    }
    return { success: false, message: desc || "Linking failed. Try getting a new link code." };
  } catch (err) {
    const msg = err?.message || "Failed to link.";
    console.warn("[plugins.service] TAK.gov token request failed:", msg);
    return { success: false, message: msg };
  }
}

/**
 * Unlink TAK.gov (clears linked state and refresh token; does not remove downloaded plugins).
 */
function unlinkTakGovAccount() {
  const manifest = loadManifest();
  const updated = {
    ...manifest.takGovLink,
    linked: false,
    refreshToken: null,
    linkCode: null,
    linkCodeExpiry: null,
    deviceCode: null,
    deviceCodeExpiry: null,
    interval: null,
    verificationUri: null,
  };
  saveManifest({ ...manifest, takGovLink: updated });
  return { success: true };
}

/**
 * List all installed plugins (from manifest; verifies file still exists).
 */
function listPlugins() {
  const manifest = loadManifest();
  const result = [];
  for (const p of manifest.plugins) {
    const filePath = path.join(PLUGINS_DIR, p.filename || "");
    const exists = fs.existsSync(filePath) && fs.statSync(filePath).isFile();
    result.push({
      ...p,
      exists,
      sizeBytes: exists ? fs.statSync(filePath).size : null,
    });
  }
  return result;
}

/**
 * Generate a unique id for a new plugin entry.
 */
function nextPluginId(plugins) {
  const ids = new Set((plugins || []).map((p) => p.id).filter(Boolean));
  let n = 1;
  while (ids.has("plugin-" + n)) n++;
  return "plugin-" + n;
}

/**
 * Add a plugin from a file path (e.g. after upload or download).
 * @param {string} sourceFilePath - path to the APK or plugin file
 * @param {{ name?: string, source?: string, atakFlavor?: string, atakVersion?: string }} meta
 * @returns {{ success: boolean, plugin?: object, error?: string }}
 */
function addPluginFromFile(sourceFilePath, meta = {}) {
  ensurePluginsDir();
  if (!fs.existsSync(sourceFilePath) || !fs.statSync(sourceFilePath).isFile()) {
    return { success: false, error: "File not found or not a file." };
  }
  const manifest = loadManifest();
  const baseName = path.basename(sourceFilePath);
  const ext = path.extname(baseName);
  const safeName = baseName.replace(/[^a-zA-Z0-9._-]/g, "_");
  const destFileName = safeName;
  const destPath = path.join(PLUGINS_DIR, destFileName);

  // If same filename exists, remove old file and manifest entry
  const existing = manifest.plugins.find((p) => p.filename === destFileName);
  if (existing) {
    try {
      const oldPath = path.join(PLUGINS_DIR, existing.filename);
      if (fs.existsSync(oldPath)) fs.unlinkSync(oldPath);
    } catch (_) {}
    manifest.plugins = manifest.plugins.filter((p) => p.id !== existing.id);
  }

  try {
    fs.copyFileSync(sourceFilePath, destPath);
  } catch (err) {
    return { success: false, error: err?.message || "Failed to copy file." };
  }

  const stat = fs.statSync(destPath);
  const id = nextPluginId(manifest.plugins);
  const plugin = {
    id,
    name: meta.name || path.basename(destFileName, ext) || destFileName,
    filename: destFileName,
    size: stat.size,
    downloadedAt: new Date().toISOString(),
    source: meta.source || "upload",
    atakFlavor: meta.atakFlavor || null,
    atakVersion: meta.atakVersion || null,
  };
  manifest.plugins.push(plugin);
  saveManifest(manifest);
  return { success: true, plugin };
}

/**
 * Add a plugin from a URL (download and store).
 * @param {string} downloadUrl - URL to the plugin file (e.g. from TAK.gov or direct link)
 * @param {{ name?: string, source?: string, atakFlavor?: string, atakVersion?: string }} meta
 * @returns {Promise<{ success: boolean, plugin?: object, error?: string }>}
 */
async function addPluginFromUrl(downloadUrl, meta = {}) {
  const axios = require("axios");
  const manifest = loadManifest();
  ensurePluginsDir();

  let response;
  try {
    response = await axios.get(downloadUrl, {
      responseType: "arraybuffer",
      timeout: 120000,
      maxContentLength: 500 * 1024 * 1024, // 500 MB
      validateStatus: (status) => status === 200,
    });
  } catch (err) {
    const msg = err?.response?.status
      ? `HTTP ${err.response.status}`
      : err?.message || "Download failed.";
    return { success: false, error: msg };
  }

  const buffer = Buffer.from(response.data);
  const contentType = response.headers["content-type"] || "";
  const contentDisp = response.headers["content-disposition"] || "";
  let baseName = "plugin.apk";
  const match = contentDisp.match(/filename[*]?=(?:UTF-8'')?["']?([^"'\s;]+)/i) || [];
  if (match[1]) baseName = match[1].trim();
  else if (contentType.includes("octet-stream") || downloadUrl) {
    try {
      const u = new URL(downloadUrl);
      const pathname = u.pathname || "";
      const seg = pathname.split("/").filter(Boolean).pop();
      if (seg && /\.(apk|zip|jar)$/i.test(seg)) baseName = seg;
    } catch (_) {}
  }
  const safeName = baseName.replace(/[^a-zA-Z0-9._-]/g, "_") || "plugin.apk";
  const destPath = path.join(PLUGINS_DIR, safeName);

  const existing = manifest.plugins.find((p) => p.filename === safeName);
  if (existing) {
    try {
      const oldPath = path.join(PLUGINS_DIR, existing.filename);
      if (fs.existsSync(oldPath)) fs.unlinkSync(oldPath);
    } catch (_) {}
    manifest.plugins = manifest.plugins.filter((p) => p.id !== existing.id);
  }

  try {
    fs.writeFileSync(destPath, buffer);
  } catch (err) {
    return { success: false, error: err?.message || "Failed to write file." };
  }

  const stat = fs.statSync(destPath);
  const id = nextPluginId(manifest.plugins);
  const plugin = {
    id,
    name: meta.name || path.basename(safeName, path.extname(safeName)) || safeName,
    filename: safeName,
    size: stat.size,
    downloadedAt: new Date().toISOString(),
    source: meta.source || "tak.gov",
    atakFlavor: meta.atakFlavor || null,
    atakVersion: meta.atakVersion || null,
  };
  manifest.plugins.push(plugin);
  saveManifest(manifest);
  return { success: true, plugin };
}

/**
 * Delete a plugin by id: remove from manifest and delete file.
 * @param {string} id - plugin id from manifest
 * @returns {{ success: boolean, error?: string }}
 */
function deletePlugin(id) {
  const manifest = loadManifest();
  const plugin = manifest.plugins.find((p) => p.id === id);
  if (!plugin) {
    return { success: false, error: "Plugin not found." };
  }
  const filePath = path.join(PLUGINS_DIR, plugin.filename);
  try {
    if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
  } catch (err) {
    console.warn("[plugins.service] Failed to delete file:", filePath, err?.message || err);
  }
  manifest.plugins = manifest.plugins.filter((p) => p.id !== id);
  saveManifest(manifest);
  return { success: true };
}

/**
 * Get absolute path to a plugin file by id (for streaming/serve).
 */
function getPluginFilePath(id) {
  const manifest = loadManifest();
  const plugin = manifest.plugins.find((p) => p.id === id);
  if (!plugin) return null;
  const filePath = path.join(PLUGINS_DIR, plugin.filename);
  return fs.existsSync(filePath) && fs.statSync(filePath).isFile() ? filePath : null;
}

module.exports = {
  PLUGINS_DIR,
  MANIFEST_PATH,
  ensurePluginsDir,
  getTakGovLinkState,
  linkTakGovAccount,
  unlinkTakGovAccount,
  listPlugins,
  addPluginFromFile,
  addPluginFromUrl,
  deletePlugin,
  getPluginFilePath,
};
